### ISSUE TITLE
No sound and video plays quickly

### ISSUE THREAD

**Issue by kubco2** [brainfoolong/omxwebgui#1]
Hello,

I have problem, that when I start video it plays quickly and doesnt have audio output.
I can see omx print commands when I click on some button in webgui, but nothing changes.
If I remove "< $3" from omxplayer line in omx-start.sh, video plays normally, but commands doesnt work.

Raspberry pi 2

Can you help please?

Thanks,
Jakub

**Comment by brainfoolong** [comment]
Have you tried the "double speed fix" option?

**Comment by kubco2** [comment]
omg I'm blind ... I read all files, but no luck. In the end in webgui is that option ....
I apologize, it works now.

**Comment by brainfoolong** [comment]
Great :)
