### ISSUE TITLE
french accent on windows share

### ISSUE THREAD

**Issue by drchewb** [brainfoolong/omxwebgui#5]
Hi,
I had to add
setlocale(LC_CTYPE, "fr_FR.UTF-8");
at start of index.php to get video launchs that have accents in the filename (à é è ...)

**Comment by brainfoolong** [comment]
Ok, i'll do some tests for this special case.

**Comment by brainfoolong** [comment]
This issue should be fixed in v2. https://github.com/brainfoolong/omxwebgui-v2. If you still have troubles send me a new issue on the v2 issue page. Thanks.
